# Generated by Django 5.0.2 on 2024-02-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_otpchecked_user_otpchecked_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchecked',
            name='is_block',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
