# Generated by Django 5.0.2 on 2024-02-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otpchecked_is_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpchecked',
            name='is_block',
        ),
    ]
