# Generated by Django 5.0.2 on 2024-02-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_otpchecked_is_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchecked',
            name='block',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
