# Generated by Django 5.0.2 on 2024-03-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تاریخ تولد'),
        ),
    ]
