# Generated by Django 5.0.2 on 2024-04-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_address_house_number_address_floor_address_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='country',
            new_name='county',
        ),
    ]
