# Generated by Django 5.0.2 on 2024-04-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_address_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
