# Generated by Django 5.0.2 on 2024-04-22 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_address_house_number_alter_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Address',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
