# Generated by Django 5.0.2 on 2024-04-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_user_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
