# Generated by Django 5.0.2 on 2024-02-06 19:15

import ckeditor.fields
import django.db.models.deletion
import django_jalali.db.models
import products.DiscountValidators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('slug1', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('sub_name', models.CharField(max_length=100, null=True, verbose_name='توضیحات کلی و کوتاه')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(upload_to='products/%Y/%M/%d', verbose_name='عکس اصلی')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود است یا خیر')),
                ('desc', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('discount', models.PositiveIntegerField(default=0, validators=[products.DiscountValidators.MaxDiscount], verbose_name='تخفیف')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('total_sale', models.PositiveIntegerField(default=0, verbose_name='آمار کل خرید محصول')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_product_rel', to='products.brand', verbose_name='برند محصول')),
                ('category', models.ManyToManyField(related_name='categories_realted', to='products.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='extraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='', verbose_name='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_image_product', to='products.product', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
