# Generated by Django 5.0.2 on 2024-02-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug1',
            new_name='slug',
        ),
    ]
