# Generated by Django 5.0.2 on 2024-02-10 15:30

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_seen_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seen_user',
        ),
        migrations.CreateModel(
            name='SeenProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_product', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
