# Generated by Django 5.0.2 on 2024-02-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_categorysecond_product_category2'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorysecond',
            name='Parent_Cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents_sub', to='products.category'),
        ),
    ]
