# Generated by Django 5.0.2 on 2024-02-16 17:14

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_categorysecond_parent_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('Parent_Cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_sub_main', to='products.category')),
                ('Parent_Cat_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_sub_two', to='products.categorysecond')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category3',
            field=models.ManyToManyField(related_name='category_subs', to='products.categorysub'),
        ),
    ]
