# Generated by Django 5.0.2 on 2024-02-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_variantproduct_color_alter_variantproduct_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('none', 'None'), ('XXSmall', 'XXSmall'), ('XSmall', 'XSmall'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XLarge', 'XLarge'), ('XXLarge', 'XXLarge'), ('XXXLarge', 'XXXLarge')], default='Medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='weight',
            name='number',
            field=models.CharField(choices=[('None', 'هیچکدام'), ('fifty', '50'), ('seventyfive', '75'), ('Hundred', '100'), ('onehandredfifty', '150'), ('twoHundred', '200'), ('threeHundred', '300'), ('fourHundred', '400'), ('fiveHundred', '500'), ('sixHundred', '600'), ('sevenHundred', '700'), ('Thousand', '1'), ('twoThousand', '2'), ('threeThousand', '3')], default='fifty', max_length=20),
        ),
    ]
