# Generated by Django 5.0.2 on 2024-02-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_size_name_alter_weight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='Unit',
            field=models.CharField(choices=[('None', 'هیچکدام'), ('gram', 'g'), ('kilogram', 'kg')], default='gram', max_length=40),
        ),
    ]
