# Generated by Django 5.0.2 on 2024-02-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('None', 'none'), ('color', 'Color'), ('Size', 'size'), ('Weight', 'weight')], default='None', max_length=20),
        ),
    ]
