# Generated by Django 5.0.2 on 2024-02-24 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_product', to='products.weight'),
        ),
    ]
