# Generated by Django 5.0.2 on 2024-02-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_weight_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='number',
            field=models.CharField(choices=[('None', 'هیچکدام'), ('fifty', '50'), ('seventyfive', '75'), ('ninetyfive', '95'), ('eightyfive', '85'), ('Hundred', '100'), ('onehandredtowenty', '120'), ('onehandredfifty', '150'), ('twoHundred', '200'), ('threeHundred', '300'), ('fourHundred', '400'), ('fiveHundred', '500'), ('sixHundred', '600'), ('sevenHundred', '700'), ('Thousand', '1'), ('twoThousand', '2'), ('threeThousand', '3')], default='fifty', max_length=20),
        ),
    ]
