# Generated by Django 5.0.2 on 2024-02-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_weight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='paking',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='weight',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
