# Generated by Django 5.0.2 on 2024-02-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_weight_paking_weight_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='number',
            field=models.CharField(choices=[('None', 'هیچکدام'), ('50', '50'), ('75', '75'), ('95', '95'), ('85', '85'), ('100', '100'), ('120', '120'), ('150', '150'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500'), ('600', '600'), ('700', '700'), ('1', '1'), ('2', '2'), ('3', '3')], default='85', max_length=20),
        ),
    ]
