# Generated by Django 5.0.2 on 2024-02-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_weight_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='number',
        ),
    ]
