# Generated by Django 5.0.2 on 2024-02-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_rename_number_weight_from_number_weight_to_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
