# Generated by Django 5.0.2 on 2024-03-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category3',
        ),
    ]
