# Generated by Django 5.0.2 on 2024-03-04 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_product_category_remove_product_category2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_realted', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_2', to='products.categorysecond'),
        ),
        migrations.AddField(
            model_name='product',
            name='category3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_subs', to='products.categorysub'),
        ),
    ]
