# Generated by Django 5.0.2 on 2024-03-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_color_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='size',
        ),
    ]
