# Generated by Django 5.0.2 on 2024-03-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_remove_color_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='size',
            field=models.ManyToManyField(related_name='color_size', to='products.size'),
        ),
    ]
