# Generated by Django 5.0.2 on 2024-03-26 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_color_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantproduct',
            name='size',
        ),
    ]
