# Generated by Django 5.0.2 on 2024-03-26 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantproduct',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='var_size', to='products.size'),
        ),
    ]
