# Generated by Django 5.0.2 on 2024-03-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_remove_product_color_product_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantProduct',
        ),
    ]
