# Generated by Django 5.0.2 on 2024-03-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_delete_variantproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('None', 'none'), ('قرمز', 'red'), ('آبی', 'blue'), ('green', 'yellow'), ('yellow', 'red'), ('black', 'black'), ('orange', 'orange'), ('white', 'white')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='product_color', to='products.color'),
        ),
    ]
