# Generated by Django 5.0.2 on 2024-03-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0044_alter_color_name_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('None', 'none'), ('قرمز', 'red'), ('آبی', 'آبی'), ('green', 'yellow'), ('yellow', 'red'), ('black', 'black'), ('orange', 'orange'), ('white', 'white')], default='None', max_length=20),
        ),
    ]
