# Generated by Django 5.0.2 on 2024-04-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0050_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products/brand/%Y/%M/%d'),
        ),
    ]
