# Generated by Django 5.0.2 on 2024-04-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0052_variantproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='size',
        ),
    ]
