# Generated by Django 5.0.2 on 2024-04-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0053_remove_color_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
