# Generated by Django 5.0.2 on 2024-04-07 05:50

import django.db.models.deletion
import django_jalali.db.models
import products.DiscountValidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0055_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('None', 'none'), ('red', 'red'), ('blue', 'blue'), ('yellow', 'yellow'), ('green', 'green'), ('black', 'black'), ('orange', 'orange'), ('white', 'white')], default='None', max_length=20),
        ),
        migrations.CreateModel(
            name='VariantColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField(default=0, validators=[products.DiscountValidators.PriceError])),
                ('discount', models.PositiveIntegerField(default=0, validators=[products.DiscountValidators.MaxDiscount])),
                ('stock', models.PositiveIntegerField(default=0, validators=[products.DiscountValidators.StockError])),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='var_color', to='products.color')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariantSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('updated', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField(default=0, validators=[products.DiscountValidators.PriceError])),
                ('discount', models.PositiveIntegerField(default=0, validators=[products.DiscountValidators.MaxDiscount])),
                ('stock', models.PositiveIntegerField(default=0, validators=[products.DiscountValidators.StockError])),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='var_size', to='products.size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='VariantProduct',
        ),
    ]
