# Generated by Django 5.0.2 on 2024-04-07 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0056_alter_color_name_variantcolor_variantsize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantcolor',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='varColorSize', to='products.size'),
        ),
    ]
