# Generated by Django 5.0.2 on 2024-04-07 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0057_variantcolor_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='VarColor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productVarColor', to='products.variantcolor'),
        ),
        migrations.AddField(
            model_name='product',
            name='VarSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productVarSize', to='products.variantsize'),
        ),
    ]
