# Generated by Django 5.0.2 on 2024-04-07 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0058_product_varcolor_product_varsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='VarColor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='VarSize',
        ),
        migrations.AddField(
            model_name='variantcolor',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductVarColor', to='products.product'),
        ),
        migrations.AddField(
            model_name='variantsize',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProductVarSize', to='products.product'),
        ),
    ]
