# Generated by Django 5.0.2 on 2024-04-07 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0062_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_replay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='replay_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay_comment', to='products.comment'),
        ),
    ]
