# Generated by Django 5.0.2 on 2024-04-08 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0064_alter_comment_replay_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
