# Generated by Django 5.0.2 on 2024-04-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0067_product_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_weight',
        ),
    ]
