# Generated by Django 5.0.2 on 2024-04-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0068_remove_product_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='img',
            field=models.ImageField(null=True, upload_to='products/brand/%Y/%M/%d'),
        ),
    ]
