# Generated by Django 5.0.2 on 2024-04-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0069_alter_brand_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantproduct',
            old_name='price',
            new_name='unit_price',
        ),
    ]
