# Generated by Django 5.0.2 on 2024-04-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0070_rename_price_variantproduct_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantproduct',
            old_name='unit_price',
            new_name='price',
        ),
    ]
