# Generated by Django 5.0.2 on 2024-05-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0072_delete_seenproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantproduct',
            name='color',
        ),
    ]
