# Generated by Django 5.0.2 on 2024-05-03 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0073_remove_variantproduct_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='var_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='var_product_like', to='products.variantproduct'),
        ),
    ]
