# Generated by Django 5.0.2 on 2024-02-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buy',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
