# Generated by Django 5.0.2 on 2024-02-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='err',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
