# Generated by Django 5.0.2 on 2024-02-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_bank_order_cardnumber_order_tracking_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profit',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
