# Generated by Django 5.0.2 on 2024-04-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
    ]
