# Generated by Django 5.0.2 on 2024-05-03 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_address'),
        ('products', '0074_like_var_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='var_product_order_item', to='products.variantproduct'),
        ),
    ]
