# Generated by Django 5.0.2 on 2024-04-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
